### ISSUE TITLE
Setup Unity Project

### ISSUE THREAD

**Issue by anchitd10** [upes-open/OSoC24-UPES-AR-Tour#1]
Initialize a new Unity project with the necessary settings and configurations for AR development along with version control

-Make sure to add .gitignore file for Unity
-Make sure you are using the latest version of git

**Comment by anchitd10** [comment]
Assigned

**Comment by the25thjin** [comment]
assign it to me as well

**Comment by sanskarrathore15** [comment]
assign this to me please
