### ISSUE TITLE
Design UI elements

### ISSUE THREAD

**Issue by anchitd10** [upes-open/OSoC24-UPES-AR-Tour#3]
Create and style the user interface elements for the AR experience in Unity.

**Comment by sanskarrathore15** [comment]
assign this to me please

**Comment by anchitd10** [comment]
assigned

**Comment by rampantvoid** [comment]
hi can you assign this to me

**Comment by anchitd10** [comment]
> assigned

assigned

**Comment by anchitd10** [comment]
> hi can you assign this to me

assigned
